version: '3'
services:
  strapi:
    build: ./strapi/
    ports:
      - '1337:1337'
    volumes:
      - /gatsby/node_modules
  gatsby:
    build: ./gatsby/
    ports:
      - '8000:8000'
    volumes:
      - /gatsby/node_modules
      - ./gatsby:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - ENABLE_GATSBY_REFRESH_ENDPOINT=true
    depends_on:
      - 'strapi'
