version: '3'
services:
  gatsby:
    build:
      context: ./gatsby
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - ENABLE_GATSBY_REFRESH_ENDPOINT=true
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '1337:1337'
