version: '3'
services:
  gatsby:
    build:
      context: .
      dockerfile: ./gatsby/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - ENABLE_GATSBY_REFRESH_ENDPOINT=true
  strapi:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: strapi/strapi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
